version: '3.4'

services:
  tourist:
    image: tourist
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 tourist\manage.py runserver 0.0.0.0:8001 --nothreading --noreload"]
    ports:
      - 8001:8001
      - 5678:5678
