# Generated by Django 4.2.3 on 2023-07-09 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('rating', models.FloatField(null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='touristapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dialogue_id', models.IntegerField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('message', models.TextField(null=True)),
                ('replies', models.IntegerField(null=True)),
                ('reply_to_msg_id', models.IntegerField(null=True)),
                ('reply_to_top_id', models.IntegerField(null=True)),
                ('reactions', models.CharField(blank=True, max_length=200, null=True)),
                ('max_id', models.IntegerField(null=True)),
                ('categories', models.ManyToManyField(blank=True, to='touristapp.category')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='touristapp.channel')),
                ('flags', models.ManyToManyField(blank=True, to='touristapp.flag')),
                ('from_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='touristapp.user')),
                ('tags', models.ManyToManyField(blank=True, to='touristapp.tag')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='touristapp.location'),
        ),
    ]
